/**
 * wasm-loader.js
 * Single responsibility: load the WASM math core and expose it as MathCore.
 * Falls back to math/fallback.js (pure JS) if WASM is unavailable.
 * No DOM access. No routing.
 */

var MathCore = (function () {

  var _wasm     = null;   // compiled WASM instance exports
  var _ready    = false;
  var _fallback = false;  // true when using pure-JS fallback

  // ── WASM load ────────────────────────────────────────────────────

  function load() {
    return new Promise(function (resolve) {
      // Attempt to load the compiled WASM module
      // The WASM glue file (math_core.js generated by Emscripten) sets
      // window.MathCoreWasm when ready.
      var script = document.createElement('script');
      script.src = 'wasm/math_core.js';

      script.onload = function () {
        if (typeof window.MathCoreWasm === 'undefined') {
          _useFallback(resolve);
          return;
        }
        window.MathCoreWasm().then(function (instance) {
          _wasm   = instance;
          _ready  = true;
          console.log('[MathCore] WASM loaded');
          resolve();
        }).catch(function () { _useFallback(resolve); });
      };

      script.onerror = function () { _useFallback(resolve); };
      document.head.appendChild(script);
    });
  }

  function _useFallback(resolve) {
    _fallback = true;
    _ready    = true;
    console.log('[MathCore] Using JS fallback');
    resolve();
  }

  // ── Dispatcher: routes to WASM or fallback ────────────────────────
  // Every function below calls _wasm.X if WASM loaded, else MathFallback.X

  function _call(wasmFn, fallbackFn, args) {
    if (_wasm && typeof _wasm[wasmFn] === 'function') {
      return _wasm[wasmFn].apply(null, args);
    }
    if (typeof MathFallback !== 'undefined' && typeof MathFallback[fallbackFn] === 'function') {
      return MathFallback[fallbackFn].apply(null, args);
    }
    console.error('[MathCore] No implementation for', wasmFn);
    return null;
  }

  // ── Public API ───────────────────────────────────────────────────

  return {
    load: load,
    isReady:    function () { return _ready; },
    usingWasm:  function () { return _ready && !_fallback; },

    /**
     * Generate one exercise for the given topic and difficulty.
     * Returns a plain JS object (parsed from JSON string from WASM).
     * @param  {string} topicId    e.g. 'equations1'
     * @param  {number} difficulty 1–5
     * @return {object}            { statement, equation, answer, hints }
     */
    generateExercise: function (topicId, difficulty) {
      return _call('generate_exercise', 'generateExercise', [topicId, difficulty]);
    },

    /**
     * Validate a student answer against the expected answer for a topic.
     * Returns true if algebrically equivalent.
     * @param  {string} topicId
     * @param  {string} studentAnswer  raw string from input
     * @param  {string} correctAnswer  as returned by generateExercise
     * @return {boolean}
     */
    validate: function (topicId, studentAnswer, correctAnswer) {
      return _call('validate_answer', 'validate', [topicId, studentAnswer, correctAnswer]);
    },

    /**
     * Analyse what the student did wrong and return a hint index (1–3).
     * 0 means no specific analysis available.
     * @param  {string} topicId
     * @param  {string} studentAnswer
     * @param  {string} correctAnswer
     * @return {number}
     */
    analyzeError: function (topicId, studentAnswer, correctAnswer) {
      return _call('analyze_error', 'analyzeError', [topicId, studentAnswer, correctAnswer]);
    },

    /**
     * Given a history of booleans (correct/wrong), return next difficulty (1–5).
     * @param  {boolean[]} history  last N attempts
     * @return {number}
     */
    nextDifficulty: function (history) {
      return _call('next_difficulty', 'nextDifficulty', [history]);
    },
  };

})();
